### ISSUE TITLE
webpage render problem

### ISSUE THREAD

**Issue by darshucreed** [Manila-Gauns/cordapp-insuranceClaim#1]
After deploying the nodes and the servers , the web page will display then when i click on " insuranceClaim " button in the localhost:10009 the page with only header will come rest of the page will come and  disappear

**Comment by ManilaGauns** [comment]
on localhost:10009, there is an 'Apply' button along with the headers. 


![image](https://user-images.githubusercontent.com/43163570/55952549-82fd1b00-5c77-11e9-8551-8f56a603cf55.png)

You need to click on it and fill in the details on the pop up form in order to proceed. 


![image](https://user-images.githubusercontent.com/43163570/55952680-cb1c3d80-5c77-11e9-88ba-8033c34b0527.png)



@darshucreed let me know if you face any other issue.

**Comment by darshucreed** [comment]
thanks for the response i will let you know as soon as i check it

**Comment by gregorydaval345** [comment]
Heyy @darshucreed   , Good day. Were you able to fix the Render issue ?
Let me know please. Wanna fix it.

**Comment by Oliviuu** [comment]
Has anyone been able to get the 'Apply' button, it just doesn't appear anymore.
